### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by droter** [unr-arl/mbplanner_ws#3]
Thanks for putting this package together.  

I ran into a compile error on kinetic:

This is the tail end of the message.  The start scrolls off the terminal:
/home/matt/ros/mbplanner_ws/src/sim/rotors_simulator/rotors_gazebo_plugins/src/gazebo_odometry_plugin.cpp:320:9: error: ‘gazebo_pose’ was not declared in this scope
         gazebo_pose.pos.x);
         ^
/home/matt/ros/mbplanner_ws/src/sim/rotors_simulator/rotors_gazebo_plugins/src/gazebo_odometry_plugin.cpp:336:9: error: ‘gazebo_linear_velocity’ was not declared in this scope
         gazebo_linear_velocity.x);
         ^
/home/matt/ros/mbplanner_ws/src/sim/rotors_simulator/rotors_gazebo_plugins/src/gazebo_odometry_plugin.cpp:343:9: error: ‘gazebo_angular_velocity’ was not declared in this scope
         gazebo_angular_velocity.x);
         ^
make[2]: *** [CMakeFiles/rotors_gazebo_gps_plugin.dir/src/gazebo_gps_plugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/rotors_gazebo_gps_plugin.dir/all] Error 2
/home/matt/ros/mbplanner_ws/src/sim/rotors_simulator/rotors_gazebo_plugins/src/gazebo_ros_interface_plugin.cpp: In destructor ‘virtual gazebo::GazeboRosInterfacePlugin::~GazeboRosInterfacePlugin()’:
/home/matt/ros/mbplanner_ws/src/sim/rotors_simulator/rotors_gazebo_plugins/src/gazebo_ros_interface_plugin.cpp:36:3: error: ‘DisconnectWorldUpdateBegin’ is not a member of ‘gazebo::event::Events’
   event::Events::DisconnectWorldUpdateBegin(updateConnection_);
   ^
make[2]: *** [CMakeFiles/rotors_gazebo_controller_interface.dir/src/gazebo_controller_interface.cpp.o] Error 1
make[1]: *** [CMakeFiles/rotors_gazebo_controller_interface.dir/all] Error 2
make[2]: *** [CMakeFiles/rotors_gazebo_lidar_plugin.dir/src/external/gazebo_lidar_plugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/rotors_gazebo_lidar_plugin.dir/all] Error 2
make[2]: *** [CMakeFiles/rotors_gazebo_odometry_plugin.dir/src/gazebo_odometry_plugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/rotors_gazebo_odometry_plugin.dir/all] Error 2
make[2]: *** [CMakeFiles/rotors_gazebo_ros_interface_plugin.dir/src/gazebo_ros_interface_plugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/rotors_gazebo_ros_interface_plugin.dir/all] Error 2
make: *** [all] Error 2

Am I missing a required package?

**Comment by MihirDharmadhikari** [comment]
Hi @droter, thank you for raising this issue.
Are you using gazebo 9 or the default gazebo version which comes with ROS Kinetic?

**Comment by droter** [comment]
I am using:
Gazebo multi-robot simulator, version 9.14.0

**Comment by MihirDharmadhikari** [comment]
I see you are using gazebo 9. In this case, can you try using the melodic-devel branch of this repository? It is meant to work with gazebo 9 which is generally used with ROS melodic hence the branch name. The instructions for compiling the same are given in the README.md file. Do get back if you face any issues.

**Comment by marcelino-pensa** [comment]
I can confirm that it works on `melodic-devel` using gazebo `9.13.0` in ROS-Kinetic. Maybe add a comment to the README about this?
BTW, I also had trouble compiling in `master`, so I had to switch to `melodic-devel` to fix this.

**Comment by MihirDharmadhikari** [comment]
Thank you @marcelino-pensa for confirming this. I will add this instruction to the README.

**Comment by droter** [comment]
Getting closer.  Only 1 package failing now:
Errors     << rotors_gazebo_plugins:make /home/matt/ros/mbplanner_ws/logs/rotors_gazebo_plugins/build.make.009.log                                                     
In file included from /home/matt/ros/mbplanner_ws/src/sim/rotors_simulator/rotors_gazebo_plugins/src/gazebo_pressure_plugin.cpp:18:0:
/home/matt/ros/mbplanner_ws/src/sim/rotors_simulator/rotors_gazebo_plugins/include/rotors_gazebo_plugins/gazebo_pressure_plugin.h:22:26: fatal error: glog/logging.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/rotors_gazebo_pressure_plugin.dir/src/gazebo_pressure_plugin.cpp.o] Error 1
make[1]: *** [CMakeFiles/rotors_gazebo_pressure_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2

**Comment by MihirDharmadhikari** [comment]
Hi, do you have the glog library installed? You can install it with `sudo apt-get install libgoogle-glog-dev`.

**Comment by droter** [comment]
This is really cool.  It is working now.  Thanks for your help.

**Comment by MihirDharmadhikari** [comment]
You are welcome!
